# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'orderly'
require 'capybara'
require 'test_app'

RSpec.configure do |config|
  if defined?(RSpec::Core::Version) && RSpec::Core::Version::STRING.to_f < 3.0
    config.treat_symbols_as_metadata_keys_with_true_values = true
  end

  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.mock_with :mocha
end

require "webdrivers" if ENV["DRIVER"] == "selenium_chrome_headless"
Capybara.server = :webrick if Capybara.respond_to?(:server=)
